window.HXE_PALETTES = [
  {
    id: "cream-mint-macaron",
    name: "奶油薄荷泡芙",
    category: "macaron",
    mood: "柔和、甜點感、親切",
    usage: "適合手作品牌、甜點頁、生活風格貼文。",
    colors: ["#f7e6d3", "#cfe8d5", "#a7d8de", "#f3b6bd", "#fff9ef"],
    score: 94,
  },
  {
    id: "soft-lilac-sugar",
    name: "紫糖霧光",
    category: "macaron",
    mood: "夢幻、輕盈、溫柔",
    usage: "適合美妝、香氛、療癒系內容。",
    colors: ["#efe3ff", "#cbb7f0", "#ffd2e1", "#fff0bd", "#f8fbff"],
    score: 91,
  },
  {
    id: "cement-olive-home",
    name: "水泥橄欖宅",
    category: "interior",
    mood: "安靜、成熟、現代裝潢",
    usage: "適合室內設計、家具型錄、簡約作品集。",
    colors: ["#d8d2c4", "#8c927f", "#454d43", "#eee9de", "#b85c45"],
    score: 96,
  },
  {
    id: "linen-walnut-studio",
    name: "亞麻胡桃工作室",
    category: "interior",
    mood: "自然、穩重、有質感",
    usage: "適合咖啡店、選物店、品牌提案。",
    colors: ["#eee6d8", "#c9b79c", "#866f55", "#3f4a44", "#d98b65"],
    score: 93,
  },
  {
    id: "dopamine-blue-pop",
    name: "快樂藍爆米花",
    category: "dopamine",
    mood: "高飽和、活潑、社群感",
    usage: "適合活動視覺、短影音封面、促銷貼文。",
    colors: ["#1268ff", "#ffdf3d", "#ff4f8b", "#12d6a1", "#10131f"],
    score: 90,
  },
  {
    id: "candy-neon-market",
    name: "糖果霓虹市集",
    category: "dopamine",
    mood: "吸睛、年輕、強烈",
    usage: "適合潮流品牌、展覽、快閃活動。",
    colors: ["#ff3d6e", "#8b5cff", "#1ee3cf", "#ffe76b", "#241933"],
    score: 89,
  },
  {
    id: "tokyo-early-morning",
    name: "東京清晨",
    category: "minimal",
    mood: "冷靜、清爽、留白",
    usage: "適合儀表板、SaaS、知識產品。",
    colors: ["#eef4f7", "#b8c8d2", "#5d7482", "#20313a", "#d86f52"],
    score: 95,
  },
  {
    id: "ink-rice-paper",
    name: "墨線宣紙",
    category: "minimal",
    mood: "東方、克制、耐看",
    usage: "適合文化內容、文字型網站、作品展示。",
    colors: ["#f4f1ea", "#c8c0b3", "#2d302f", "#73816f", "#b6463c"],
    score: 92,
  },
  {
    id: "ocean-tech-panel",
    name: "深海科技艙",
    category: "tech",
    mood: "專業、未來感、穩定",
    usage: "適合 AI 工具、開發者產品、深色介面。",
    colors: ["#07131f", "#123a52", "#1b9aaa", "#9ee493", "#f4d35e"],
    score: 91,
  },
  {
    id: "signal-coral",
    name: "訊號珊瑚",
    category: "tech",
    mood: "科技、清楚、帶一點溫度",
    usage: "適合資料視覺化、產品後台、報告頁。",
    colors: ["#17252a", "#2b7a78", "#3aafa9", "#def2f1", "#ff7f6e"],
    score: 90,
  },
  {
    id: "peach-evening-ad",
    name: "杏桃晚報",
    category: "editorial",
    mood: "編輯感、溫暖、柔亮",
    usage: "適合電子報、社群長圖、媒體品牌。",
    colors: ["#fff1df", "#f6b28d", "#d96c59", "#6d4c41", "#273036"],
    score: 93,
  },
  {
    id: "berry-espresso-cover",
    name: "莓果濃縮封面",
    category: "editorial",
    mood: "濃烈、時髦、記憶點強",
    usage: "適合封面設計、展演視覺、品牌主視覺。",
    colors: ["#2a1721", "#7d2345", "#d64161", "#f2a65a", "#f7e7ce"],
    score: 88,
  },
];

window.HXE_PALETTE_CATEGORIES = [
  { id: "all", label: "全部" },
  { id: "macaron", label: "馬卡龍" },
  { id: "interior", label: "現代裝潢" },
  { id: "dopamine", label: "多巴胺" },
  { id: "minimal", label: "極簡" },
  { id: "tech", label: "科技" },
  { id: "editorial", label: "編輯感" },
];
